import type { Metadata } from 'next';

import './globals.css';

import { Poppins } from 'next/font/google';
import { SidebarProvider } from './_components/ui/sidebar';
import AppSidebar from './_components/app-sidebar';
import Navbar from './_components/navbar';

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body className={`${poppins.className} dark antialiased`}>
                <SidebarProvider>
                    <AppSidebar />
                    <main className="h-full w-full pl-3">
                        <Navbar />
                        {children}
                    </main>
                </SidebarProvider>
            </body>
        </html>
    );
}
